# Generated by Django 5.0.1 on 2024-01-15 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=255)),
                ('insert_datetime', models.DateTimeField(auto_now_add=True)),
                ('delete_datetime', models.DateTimeField(blank=True, null=True)),
                ('delete_status', models.BooleanField(default=False)),
                ('delete_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_deleted_by', to='authentication.customuser')),
                ('insert_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_inserted_by', to='authentication.customuser')),
            ],
        ),
    ]
