# Generated by Django 5.0.1 on 2024-03-05 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='seen_story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_datetime', models.DateTimeField(auto_now_add=True)),
                ('insert_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_story_inserted_by', to=settings.AUTH_USER_MODEL)),
                ('seen_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_story_seen_by', to=settings.AUTH_USER_MODEL)),
                ('story_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_story_story_id', to='home.story')),
            ],
        ),
    ]
