# Generated by Django 5.0.1 on 2024-04-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_seen_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seen_story',
            name='insert_by',
        ),
    ]
