# Generated by Django 5.0.1 on 2024-01-15 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_friend_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_with', to='authentication.customuser')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='authentication.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('read_datetime', models.DateTimeField(blank=True, null=True)),
                ('delete_status', models.BooleanField(default=False)),
                ('delete_datetime', models.DateTimeField(blank=True, null=True)),
                ('message_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_from', to='authentication.customuser')),
                ('message_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliver_to', to='authentication.customuser')),
            ],
        ),
    ]
