# Generated by Django 5.0.1 on 2024-05-06 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0002_alter_followers_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_content', models.TextField()),
                ('insert_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isnert_by', to=settings.AUTH_USER_MODEL)),
                ('user_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_report', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
