# Generated by Django 5.0.1 on 2024-01-15 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('caption', models.TextField()),
                ('file_1', models.FileField(blank=True, null=True, upload_to='media')),
                ('file_2', models.FileField(blank=True, null=True, upload_to='media')),
                ('file_3', models.FileField(blank=True, null=True, upload_to='media')),
                ('file_4', models.FileField(blank=True, null=True, upload_to='media')),
                ('like_count', models.IntegerField(blank=True, null=True)),
                ('comment_count', models.IntegerField(blank=True, null=True)),
                ('insert_datetime', models.DateTimeField(auto_now_add=True)),
                ('delete_datetime', models.DateTimeField(blank=True, null=True)),
                ('delete_status', models.BooleanField(default=False)),
                ('insert_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_inserted_by', to='authentication.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.customuser')),
            ],
        ),
    ]
