# Generated by Django 5.0.1 on 2024-02-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='following_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
