# Generated by Django 5.0.1 on 2024-03-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_following_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rp_otp_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rp_verify_status',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
